export const LayerActions = {
  SET_BACKGROUND_LAYERS : 'SET_BACKGROUND_LAYERS',
  SELECT_BACKGROUND_LAYER: 'SELECT_BACKGROUND_LAYER',
  ADD_LAYERS: 'ADD_LAYERS',
  SET_EXTENT: 'SET_EXTENT',
  ADD_FEATURE: 'ADD_FEATURE',
  ADD_FEATURE_LIST: 'ADD_FEATURE_LIST',
  SET_PROJECTION_SYSTEM: 'SET_PROJECTION_SYSTEM',
  SELECT_FEATURE: 'SELECT_FEATURE',
  SELECT_DATE: 'SELECT_DATE',
  TOGGLE_LAYER: 'TOGGLE_LAYER',
  SET_ACTIVE_FEATURE: 'SET_ACTIVE_FEATURE'
};
