export const ToolBoxActions = {
  SELECT_ACTION : 'SELECT_ACTION',
  SELECT_LAYERS : 'SELECT_LAYERS',
  SELECT_BBOX: 'SELECT_BBOX',
  SET_SELECTION_TYPE: 'SET_SELECTION_TYPE',
  STOP_ACTION: 'STOP_ACTION'
};

